001-web/001-web/001-net-framework/001-tutorials-curses/001-CNetFrame4MVCEntFram/Models/ViewModels/ImagesUploadViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace _001_CNetFrame4MVCEntFram.Models.ViewModels
{
    public class ImagesUploadViewModel
    {
        [Required]
        [DisplayName("Archivo 1")]
        public HttpPostedFileBase File1 { get; set; }

        [Required]
        [DisplayName("Archivo 2")]
        public HttpPostedFileBase File2 { get; set; }

        [Required]
        [DisplayName("Mi cadena")]
        public string Cadena { get; set; }
    }
}

001-web/001-web/001-net-framework/001-tutorials-curses/001-CNetFrame4MVCEntFram/Controllers/ImagesUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using _001_CNetFrame4MVCEntFram.Models.ViewModels;

namespace _001_CNetFrame4MVCEntFram.Controllers
{
    public class ImagesUploadController : Controller
    {
        // GET: ImagesUpload
        public ActionResult Index()
        {
            if (TempData["Mensaje"] != null) {
                ViewBag.Mensaje = TempData["Mensaje"].ToString();
            }
            return View();
        }

        [HttpPost]
        public ActionResult Guardar(ImagesUploadViewModel model)
        {
            string RutaSitio = Server.MapPath("~/Files");
            string PathArchivo1 = Path.Combine(RutaSitio, model.File1.FileName);
            string PathArchivo2 = Path.Combine(RutaSitio, model.File2.FileName);
            if (!ModelState.IsValid)
            {
                return View("Index", model);
            }
            model.File1.SaveAs(PathArchivo1);
            model.File1.SaveAs(PathArchivo2);
            @TempData["Mensaje"] = "Archivos guardados correctamente";
            return RedirectToAction("Index");
        }
    }
}

001-web/001-web/001-net-framework/001-tutorials-curses/001-CNetFrame4MVCEntFram/Views/ImagesUpload/Index.cshtml
@model _001_CNetFrame4MVCEntFram.Models.ViewModels.ImagesUploadViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@if (ViewBag.Mensaje != null)
{
<div class="alert alert-success">
    @ViewBag.Mensaje
</div>
}

@using (Html.BeginForm("Guardar", "ImagesUpload", FormMethod.Post, new { @role = "form", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken();
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-6">
            @Html.LabelFor(d => d.File1)
            @*<input type="file" name="File1" value="" />*@
            @Html.TextBoxFor(d => d.File1, new { type = "file" })
            @Html.ValidationMessageFor(d => d.File1, "", new { @class = "text-danger" })

            @Html.LabelFor(d => d.File2)
            @*<input type="file" name="File2" value="" />*@
            @Html.TextBoxFor(d => d.File2, new { type = "file" })
            @Html.ValidationMessageFor(d => d.File2, "", new { @class = "text-danger" })

            @Html.LabelFor(d => d.Cadena)
            @Html.TextBoxFor(d => d.Cadena, new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Cadena, "", new { @class = "text-danger" })
            <br />
            <div class="card">
                <input type="submit" class="btn btn-success" name="" value="Guardar" />
            </div>
        </div>
    </div>
}